// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr88oIreYPDAxHf8zRRHQiEu1BpS5l6-M',
    appId: '1:1075551521579:web:76b37435474cd9dc84d36e',
    messagingSenderId: '1075551521579',
    projectId: 'agapai-f703f',
    authDomain: 'agapai-f703f.firebaseapp.com',
    storageBucket: 'agapai-f703f.firebasestorage.app',
    measurementId: 'G-XPHFEXEGQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdvqwWOgxSBG5ZW2-1lMUsd52EBPjgJo',
    appId: '1:1075551521579:android:bbf5bcb5d72913b584d36e',
    messagingSenderId: '1075551521579',
    projectId: 'agapai-f703f',
    storageBucket: 'agapai-f703f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOUeKWluDBdVL0K3PeGdlcCk35-udSnvA',
    appId: '1:1075551521579:ios:788bc6b54bf1625684d36e',
    messagingSenderId: '1075551521579',
    projectId: 'agapai-f703f',
    storageBucket: 'agapai-f703f.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOUeKWluDBdVL0K3PeGdlcCk35-udSnvA',
    appId: '1:1075551521579:ios:788bc6b54bf1625684d36e',
    messagingSenderId: '1075551521579',
    projectId: 'agapai-f703f',
    storageBucket: 'agapai-f703f.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr88oIreYPDAxHf8zRRHQiEu1BpS5l6-M',
    appId: '1:1075551521579:web:4e36b1051444546684d36e',
    messagingSenderId: '1075551521579',
    projectId: 'agapai-f703f',
    authDomain: 'agapai-f703f.firebaseapp.com',
    storageBucket: 'agapai-f703f.firebasestorage.app',
    measurementId: 'G-WF4P08RNCH',
  );
}
